accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.urls import views as auth_views
from .forms import LoginForm
from . import views


app_name = 'accounts'
urlpatterns = [
    path("login/", auth_views.LoginView.as_view(authentication_form=LoginForm, redirect_authenticated_user=True), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # path("register/invite/?<uuid:invite_code>/", views.register, name="register_with_code"),
    path("register/", views.register, name="register"),
    path("password_change/", auth_views.PasswordChangeView.as_view(), name="password_change"),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset/", auth_views.PasswordResetView.as_view(success_url=reverse_lazy("accounts:password_reset_done")), name="password_reset"),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy("accounts:password_reset_complete")),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("update_user/", views.updateUser, name="update-user"),
    path("update_password/", views.update_password, name="update_password"),
    path("update_user_payment_system/", views.update_user_payment_system, name="update_user_payment_system"),
]

h_tem_invest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect


def home(request):
    return redirect('accounts:login')

urlpatterns = [
    # path('', TemplateView.as_view(template_name='home/home.html'), name='home'),
    path('', home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('user/', include('users.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('transactions/', views.transactions, name='transactions'),
    path('deposit/', views.deposit, name='deposit'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('partners/', views.partners, name='partners'),
    path('settings/', views.settings, name='settings'),
    path('filter_by_level/', views.filter_by_level, name='filter_by_level')
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from accounts.models import Partner, User
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings
from transactions.models import Transaction
from transactions.forms import TransactionForm
from services.models import Service
from django.contrib import messages
from django.core.paginator import Paginator

page = ""

@login_required
def dashboard(request):
    list_of_partner = Partner.objects.get(user=request.user).getAllUserPartners()
    list_of_active_partner = [partner for partner in list_of_partner if partner.is_active]
    inactive_partner = len(list_of_partner) - len(list_of_active_partner)
    user_infos = Partner.objects.get(user=request.user).getTotalNumberOfParternsByLevel(level=2)
    context = {
        'page': 'dashboard',
        'active_partner': list_of_active_partner,
        'inactive_partner': inactive_partner,
        'partners': list_of_partner,
    }
    return render(request, 'users/dashboard.html', context)


@login_required
def transactions(request):
    user = request.user
    user_transactions = Transaction.objects.filter(user=user)
    context = {
        'page': 'transactions',
        'user_transactions': user_transactions
    }
    return render(request, 'users/operations.html', context)


@login_required
def deposit(request):
    services = Service.objects.all()
    form = TransactionForm()
    print(request.POST)
    print(request.FILES)
    if request.method == 'POST':
        print('test')
        data = {
            'image': request.FILES['image'],
            'amount': request.POST['amount'],
            'payment_method': request.POST['payment_method'],
            'user': request.user,
            'operation': 'DE',
            'status': 'Prepared'
        }
        print(data)
        form = TransactionForm(data)
        if form.is_valid():
            print('oui')
            transaction = form.save(commit=False)
            transaction.image = request.FILES['image']
            transaction.save()
            messages.success(request, "Deposit success")
            return redirect('users:deposit')
            
    return render(request, 'users/deposit.html', {'page': 'deposit', 'services': services, 'form': form})


@login_required
def withdraw(request):
    services = Service.objects.all()
    form = TransactionForm()
    if request.method == 'POST':
        print('test')
        data = {
            'phone_to_send': request.POST['phone_to_send'],
            'amount': request.POST['amount'],
            'payment_method': request.POST['payment_method'],
            'user': request.user,
            'operation': 'WI',
            'status': 'Prepared'
        }
        print(data)
        form = TransactionForm(data)
        if form.is_valid():
            print('ok')
            transaction = form.save(commit=False)
            transaction.save()
            messages.success(request, "Withdraw success")
            return redirect('users:withdraw')
    return render(request, 'users/withdraw.html', {'page': 'withdraw', 'services': services, 'form': form})


@login_required
def partners(request):
    #level = request.GET['level'] if request.GET['level'] else ""
    level = "ALL"
    page_number = ""
    try:
        level = request.GET['level']
        level = int(level)
    except:
        pass
    current_site = get_current_site(request)
    protocol = "http"
    site_name = current_site.name
    domain = current_site.domain
    list_of_partner = Partner.objects.get(user=request.user).getAllUserPartners()
    # partners = [partner for partner in list_of_partner]
    if level == 1 or level == 2 or level == 3 or level ==4:
        level_partners = Partner.objects.get(user=request.user).getAllUsersByLevel(level)
    else:
        level_partners = [partner for partner in list_of_partner]

    list_of_active_partner = [partner for partner in list_of_partner if partner.is_active]
    inactive_partner = len(list_of_partner) - len(list_of_active_partner)
    fisrt_level_user = User.objects.filter(added_by=request.user).count()
    # print(number_of_partners)
    print(list_of_partner)

    if page_number:
        paginator = Paginator(level_partners, 5)
        level_partners = paginator.get_page(page_number)

    context = {
        'page': 'partners', 
        'partners': list_of_partner,
        'level_partners': level_partners,
        'first_level_user': fisrt_level_user,
        'protocol': protocol,
        'site_name': site_name,
        'domain': domain,
        'active_partner': list_of_active_partner,
        'inactive_partner': inactive_partner,
        'level': level
    }
    return render(request, 'users/partners.html', context)

def settings(request):
    return render(request, 'users/setting.html', {'page': 'settings'})


def filter_by_level(request):
    level = request.GET['level']
    level = int(level)
    user = request.user
    partner = Partner.objects.filter(user=user)
    # all_level_partner = partner.getTotalNumberOfParternsByLevel(level)
    all_partner = Partner.objects.get(user=request.user).getAllUserPartners()
    list_of_partner = Partner.objects.get(user=request.user).getAllUsersByLevel(level)
    list_of_active_partner = [partner for partner in all_partner if partner.is_active]
    inactive_partner = len(all_partner) - len(list_of_active_partner)
    fisrt_level_user = User.objects.filter(added_by=request.user).count()

    context = {
        'page': 'partners', 
        'partners': all_partner,
        'level_partner': list_of_partner,
        'first_level_user': fisrt_level_user,
        'active_partner': list_of_active_partner,
        'inactive_partner': inactive_partner
    }
    return render(request, 'users/partners.html', context)

users/templates/users/partials/_dashboard_section.html
{% load static %}
<div class="side-header oh">
    <div class="cross-header-bar d-xl-none">
        <span></span>
        <span></span>
        <span></span>
    </div>
    <div class="site-header-container">
        <div class="side-logo text-center">
            <a href="{% url 'users:dashboard' %}">
                <img src="{% static 'assets/images/logo/htech.png' %}" alt="logo">
            </a>
        </div>
        {% include 'users/partials/_menu.html' %}

    </div>
</div>

users/templates/users/partials/_dashboard_top.html
{% load static %}
<div class="dashboard-hero">
    <div class="header-top">
        <div class="container">
            <div class="mobile-header d-flex justify-content-between d-lg-none align-items-center">
                <div class="author">
                    <img src="{% static 'assets/images/dashboard/author.png' %}" alt="dashboard">
                </div>
                <div class="cross-header-bar">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <div class="mobile-header-content d-lg-flex flex-wrap justify-content-lg-between align-items-center">
                <ul class="support-area">
                    <!-- <li>
                        <a href="#0"><i class="flaticon-support"></i>Support</a>
                    </li>
                    <li>
                        <a href="Mailto:info@hteminvest.com"><i class="flaticon-email"></i><span class="__cf_email__" data-cfemail="fe97909891be9687978e929f909ad09d9193">[email&#160;protected]</span> </a>
                    </li> -->
                    <li>
                        <i class="flaticon-globe"></i>
                        <div class="select-area">
                            <select class="select-bar" style="display: none;">
                                <option value="en">English</option>
                                <option value="bn">French</option>
                                <!-- <option value="sp">Spanish</option> -->
                            </select>
                        </div>
                    </li>
                </ul>
                <div class="dashboard-header-right d-flex flex-wrap justify-content-center justify-content-sm-between justify-content-lg-end align-items-center">
                    <!-- <form class="dashboard-header-search mr-sm-4">
                        <label for="search"><i class="flaticon-magnifying-glass"></i></label>
                        <input type="text" placeholder="Search...">
                    </form> -->
                    <ul class="dashboard-right-menus">
                        <!-- <li>
                            <a href="#0">
                                <i class="flaticon-email-1"></i>
                                <span class="number bg-theme-2">4</span>
                            </a>
                            <div class="notification-area">
                                <div class="notifacation-header d-flex flex-wrap justify-content-between">
                                    <span>4 New Notifications</span>
                                    <a href="#0">Clear</a>
                                </div>
                                <ul class="notification-body">
                                    <li>
                                        <a href="#0">
                                            <div class="icon">
                                                <img src="{% static 'assets/images/dashboard/author.png' %}" alt="dashboard">
                                            </div>
                                            <div class="cont">
                                                <span class="title">Robinhood Pandey</span>
                                                <div class="message">Electus rem placeat perspiciatis saepe</div>
                                                <span class="info">2 Sec ago</span>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#0">
                                            <div class="icon">
                                                <img src="{% static 'assets/images/dashboard/author.png' %}" alt="dashboard">
                                            </div>
                                            <div class="cont">
                                                <span class="title">Robinhood Pandey</span>
                                                <div class="message">Electus rem placeat perspiciatis saepe</div>
                                                <span class="info">2 Sec ago</span>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#0">
                                            <div class="icon">
                                                <img src="{% static 'assets/images/dashboard/author.png' %}" alt="dashboard">
                                            </div>
                                            <div class="cont">
                                                <span class="title">Robinhood Pandey</span>
                                                <div class="message">Electus rem placeat perspiciatis saepe</div>
                                                <span class="info">2 Sec ago</span>
                                            </div>
                                        </a>
                                    </li>
                                </ul>
                                <div class="notifacation-footer text-center">
                                    <a href="#0" class="view-all">View All</a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <a href="#0">
                                <i class="flaticon-notification"></i>
                                <span class="number bg-theme">4</span>
                            </a>
                            <div class="notification-area">
                                <div class="notifacation-header d-flex flex-wrap justify-content-between">
                                    <span>4 New Notifications</span>
                                    <a href="#0">Clear</a>
                                </div>
                                <ul class="notification-body">
                                    <li>
                                        <a href="#0">
                                            <div class="icon">
                                                <i class="flaticon-man"></i>
                                            </div>
                                            <div class="cont">
                                                <span class="subtitle">New Affiliate Registered</span>
                                                <span class="info">2 Sec ago</span>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#0">
                                            <div class="icon">
                                                <i class="flaticon-atm"></i>
                                            </div>
                                            <div class="cont">
                                                <span class="subtitle">New deposit completed</span>
                                                <span class="info">2 Sec ago</span>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#0">
                                            <div class="icon">
                                                <i class="flaticon-wallet"></i>
                                            </div>
                                            <div class="cont">
                                                <span class="subtitle">New Withdraw completed</span>
                                                <span class="info">2 Sec ago</span>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#0">
                                            <div class="icon">
                                                <i class="flaticon-exchange"></i>
                                            </div>
                                            <div class="cont">
                                                <span class="subtitle">Fund Transfer Completed</span>
                                                <span class="info">2 Sec ago</span>
                                            </div>
                                        </a>
                                    </li>
                                </ul>
                                <div class="notifacation-footer text-center">
                                    <a href="#0" class="view-all">View All</a>
                                </div>
                            </div>
                        </li> -->
                        <li>
                            <a href="#0" class="author">
                                <div class="thumb">
                                    <img src="{% static 'assets/images/dashboard/user.png' %}" alt="dashboard">
                                    <span class="checked">
                                        <i class="flaticon-checked"></i>
                                    </span>
                                </div>
                                <div class="content">
                                    <h6 class="title"> {{request.user.get_full_name}} </h6>
                                    <span class="country">{{request.user.country}}</span>
                                </div>
                            </a>
                            <div class="notification-area">
                                <div class="author-header">
                                    <div class="thumb">
                                        <img src="{% static 'assets/images/dashboard/user.png' %}" alt="dashboard">
                                    </div>
                                    <h6 class="title">{{request.user.get_full_name}}</h6>
                                    <!-- <a href="#mailto:johndoe@gmail.com"><span class="__cf_email__" data-cfemail="c78da8afa9a3a8a287a0aaa6aeabe9a4a8aa">[email&#160;protected]</span></a> -->
                                </div>
                                <div class="author-body">
                                    <ul>
                                        <li>
                                            <a href="{% url 'users:settings' %}"><i class="far fa-user"></i>Profile</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'users:settings' %}"><i class="fas fa-user-edit"></i>Edit Profile</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i>Log Out</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="dashboard-hero-content text-white">
        <h3 class="title">Dashboard</h3>
        <ul class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                {{page|title }}
            </li>
        </ul>
    </div>
</div>

users/templates/users/partials/_footer.html
<div class="container-fluid sticky-bottom">
    <div class="dashboard-footer">
        <div class="d-flex flex-wrap justify-content-between m-0-15-none">
            <div class="left">
                &copy; 2023 <a href="#0">H_tem_Invest</a>  |  All right reserved.
            </div>
            <div class="right">
                <!-- <ul>
                    <li>
                        <a href="#0">Terms of use</a>
                    </li>
                    <li>
                        <a href="#0">Privacy policy</a>
                    </li>
                </ul> -->
            </div>
        </div>
    </div>
</div>

users/templates/users/partials/_header.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>H_TEM_INVEST Dashboard</title>

    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/odometer.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">

    <!-- <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" type="image/x-icon"> -->
    <link rel="shortcut icon" href="{% static 'assets/images/logo/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" /> 
</head>

users/templates/users/partials/_loader_div.html
<div class="loader">
    <div class="loader-inner">
        <div class="loader-line-wrap">
            <div class="loader-line"></div>
        </div>
        <div class="loader-line-wrap">
            <div class="loader-line"></div>
        </div>
        <div class="loader-line-wrap">
            <div class="loader-line"></div>
        </div>
        <div class="loader-line-wrap">
            <div class="loader-line"></div>
        </div>
        <div class="loader-line-wrap">
            <div class="loader-line"></div>
        </div>
    </div>
</div>
<div class="overlay"></div>

users/templates/users/partials/_loader_script.html
<script>
    $('.progress1.circle').circleProgress({
        value: .75,
        fill: {
            gradient: ['#00cca2', '#00cca2']
        },
        }).on('circle-animation-progress', function(event, progress) {
        $(this).find('strong').html(Math.round(75 * progress) + '<i>%</i>');
    });
    $('.progress2.circle').circleProgress({
        value: .90,
        fill: {
            gradient: ['#8d16e8', '#8d16e8']
        },
        }).on('circle-animation-progress', function(event, progress) {
        $(this).find('strong').html(Math.round(90 * progress) + '<i>%</i>');
    });
    $('.progress3.circle').circleProgress({
        value: .85,
        fill: {
            gradient: ['#ef764c', '#ef764c']
        },
        }).on('circle-animation-progress', function(event, progress) {
        $(this).find('strong').html(Math.round(85 * progress) + '<i>%</i>');
    });
</script>

users/templates/users/partials/_menu.html
<ul class="dashboard-menu">
    <li>
        <a href="{% url 'users:dashboard' %}" class={% if page == 'dashboard' %}"active"{% else %} {%endif%}><i class="flaticon-man"></i>Dashboard</a>
    </li>
    <li>
        <a href="{% url 'users:transactions' %}" class={% if page == 'transactions' %}"active"{% else %} {%endif%}><i class="flaticon-coin"></i>Transactions</a>
    </li>
    <li>
        <a href="{% url 'users:deposit' %}" class={% if page == 'deposit' %}"active"{% else %} {%endif%}><i class="flaticon-interest"></i>Deposits</a>
    </li>
    <li>
        <a href="{% url 'users:withdraw' %}" class={% if page == 'withdraw' %}"active"{% else %} {%endif%}><i class="flaticon-atm"></i>Withdraw</a>
    </li>
    <li>
        <a href="{% url 'users:partners' %}" class={% if page == 'partners' %}"active"{% else %} {%endif%}><i class="flaticon-deal"></i>Partners</a>
    </li>
    <li>
        <a href="{% url 'users:settings' %}" class={% if page == 'settings' %}"active"{% else %} {%endif%}><i class="flaticon-gears"></i>Settings</a>
    </li>
    <li>
        <a href="{% url 'accounts:logout' %}"><i class="flaticon-right-arrow"></i>Logout</a>
    </li>
</ul>

users/templates/users/partials/_prices.html
{% load static %}

<div class="row justify-content-center mt--85">
    <div class="col-sm-6 col-lg-2">
        <div class="dashboard-item">
            <div class="dashboard-inner">
                <div class="cont">
                    <span class="title">Total Deposit</span>
                    <h5 class="amount">{{request.user.total_amount_xaf}} XAF</h5>
                </div>
                <div class="thumb">
                    <img src="{% static 'assets/images/dashboard/dashboard1.png' %}" alt="dasboard">
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-2">
        <div class="dashboard-item">
            <div class="dashboard-inner">
                <div class="cont">
                    <span class="title">Balance</span>
                    <h5 class="amount">{{request.user.total_amount_usdt}} USDT</h5>
                </div>
                <div class="thumb">
                    <img src="{% static 'assets/images/dashboard/dashboard2.png' %}" alt="dasboard">
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-2">
        <div class="dashboard-item">
            <div class="dashboard-inner">
                <div class="cont">
                    <span class="title">Bonus Balance</span>
                    <h5 class="amount">{{request.user.total_amount_bonus_sub}} XAF</h5>
                </div>
                <div class="thumb">
                    <img src="{% static 'assets/images/dashboard/dashboard3.png' %}" alt="dasboard">
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-2">
        <div class="dashboard-item">
            <div class="dashboard-inner">
                <div class="cont">
                    <span class="title">Balance</span>
                    <h5 class="amount">{{request.user.total_amount_tron}} TRON</h5>
                </div>
                <div class="thumb">
                    <img src="{% static 'assets/images/dashboard/dashboard4.png' %}" alt="dasboard">
                </div>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-lg-2">
        <div class="dashboard-item">
            <div class="dashboard-inner">
                <div class="cont">
                    <span class="title">Total withdraw</span>
                    <h5 class="amount">{{request.user.total_amount_withdraw}} XAF</h5>
                </div>
                <div class="thumb">
                    <img src="{% static 'assets/images/dashboard/dashboard4.png' %}" alt="dasboard">
                </div>
            </div>
        </div>
    </div>
</div>

users/templates/users/partials/_scripts.html
{% load static %}
<script data-cfasync="false" src="http://pixner.net/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
   
<script src="{% static 'assets/js/modernizr-3.6.0.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'assets/js/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/odometer.min.js' %}"></script>
    <script src="{% static 'assets/js/viewport.jquery.js' %}"></script>
    <script src="{% static 'assets/js/nice-select.js' %}"></script>
    <script src="{% static 'assets/js/owl.min.js' %}"></script>
    <script src="{% static 'assets/js/paroller.js' %}"></script>
    <script src="{% static 'assets/js/chart.js' %}"></script>
    <script src="{% static 'assets/js/circle-progress.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'assets/js/new.js' %}"></script>
    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <script src="{% static 'assets/js/api.js' %}"></script>

    