accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.urls import views as auth_views
from .forms import LoginForm
from . import views


app_name = 'accounts'
urlpatterns = [
    path("login/", auth_views.LoginView.as_view(authentication_form=LoginForm, redirect_authenticated_user=True), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # path("register/invite/?<uuid:invite_code>/", views.register, name="register_with_code"),
    path("register/", views.register, name="register"),
    path("password_change/", auth_views.PasswordChangeView.as_view(), name="password_change"),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset/", auth_views.PasswordResetView.as_view(success_url=reverse_lazy("accounts:password_reset_done")), name="password_reset"),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy("accounts:password_reset_complete")),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("update_user/", views.updateUser, name="update-user"),
    path("update_password/", views.update_password, name="update_password"),
    path("update_user_payment_system/", views.update_user_payment_system, name="update_user_payment_system"),
]

h_tem_invest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect


def home(request):
    return redirect('accounts:login')

urlpatterns = [
    # path('', TemplateView.as_view(template_name='home/home.html'), name='home'),
    path('', home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('user/', include('users.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('transactions/', views.transactions, name='transactions'),
    path('deposit/', views.deposit, name='deposit'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('partners/', views.partners, name='partners'),
    path('settings/', views.settings, name='settings'),
    path('filter_by_level/', views.filter_by_level, name='filter_by_level')
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from accounts.models import Partner, User
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings
from transactions.models import Transaction
from transactions.forms import TransactionForm
from services.models import Service
from django.contrib import messages
from django.core.paginator import Paginator

page = ""

@login_required
def dashboard(request):
    list_of_partner = Partner.objects.get(user=request.user).getAllUserPartners()
    list_of_active_partner = [partner for partner in list_of_partner if partner.is_active]
    inactive_partner = len(list_of_partner) - len(list_of_active_partner)
    user_infos = Partner.objects.get(user=request.user).getTotalNumberOfParternsByLevel(level=2)
    context = {
        'page': 'dashboard',
        'active_partner': list_of_active_partner,
        'inactive_partner': inactive_partner,
        'partners': list_of_partner,
    }
    return render(request, 'users/dashboard.html', context)


@login_required
def transactions(request):
    user = request.user
    user_transactions = Transaction.objects.filter(user=user)
    context = {
        'page': 'transactions',
        'user_transactions': user_transactions
    }
    return render(request, 'users/operations.html', context)


@login_required
def deposit(request):
    services = Service.objects.all()
    form = TransactionForm()
    print(request.POST)
    print(request.FILES)
    if request.method == 'POST':
        print('test')
        data = {
            'image': request.FILES['image'],
            'amount': request.POST['amount'],
            'payment_method': request.POST['payment_method'],
            'user': request.user,
            'operation': 'DE',
            'status': 'Prepared'
        }
        print(data)
        form = TransactionForm(data)
        if form.is_valid():
            print('oui')
            transaction = form.save(commit=False)
            transaction.image = request.FILES['image']
            transaction.save()
            messages.success(request, "Deposit success")
            return redirect('users:deposit')
            
    return render(request, 'users/deposit.html', {'page': 'deposit', 'services': services, 'form': form})


@login_required
def withdraw(request):
    services = Service.objects.all()
    form = TransactionForm()
    if request.method == 'POST':
        print('test')
        data = {
            'phone_to_send': request.POST['phone_to_send'],
            'amount': request.POST['amount'],
            'payment_method': request.POST['payment_method'],
            'user': request.user,
            'operation': 'WI',
            'status': 'Prepared'
        }
        print(data)
        form = TransactionForm(data)
        if form.is_valid():
            print('ok')
            transaction = form.save(commit=False)
            transaction.save()
            messages.success(request, "Withdraw success")
            return redirect('users:withdraw')
    return render(request, 'users/withdraw.html', {'page': 'withdraw', 'services': services, 'form': form})


@login_required
def partners(request):
    #level = request.GET['level'] if request.GET['level'] else ""
    level = "ALL"
    page_number = ""
    try:
        level = request.GET['level']
        level = int(level)
    except:
        pass
    current_site = get_current_site(request)
    protocol = "http"
    site_name = current_site.name
    domain = current_site.domain
    list_of_partner = Partner.objects.get(user=request.user).getAllUserPartners()
    # partners = [partner for partner in list_of_partner]
    if level == 1 or level == 2 or level == 3 or level ==4:
        level_partners = Partner.objects.get(user=request.user).getAllUsersByLevel(level)
    else:
        level_partners = [partner for partner in list_of_partner]

    list_of_active_partner = [partner for partner in list_of_partner if partner.is_active]
    inactive_partner = len(list_of_partner) - len(list_of_active_partner)
    fisrt_level_user = User.objects.filter(added_by=request.user).count()
    # print(number_of_partners)
    print(list_of_partner)

    if page_number:
        paginator = Paginator(level_partners, 5)
        level_partners = paginator.get_page(page_number)

    context = {
        'page': 'partners', 
        'partners': list_of_partner,
        'level_partners': level_partners,
        'first_level_user': fisrt_level_user,
        'protocol': protocol,
        'site_name': site_name,
        'domain': domain,
        'active_partner': list_of_active_partner,
        'inactive_partner': inactive_partner,
        'level': level
    }
    return render(request, 'users/partners.html', context)

def settings(request):
    return render(request, 'users/setting.html', {'page': 'settings'})


def filter_by_level(request):
    level = request.GET['level']
    level = int(level)
    user = request.user
    partner = Partner.objects.filter(user=user)
    # all_level_partner = partner.getTotalNumberOfParternsByLevel(level)
    all_partner = Partner.objects.get(user=request.user).getAllUserPartners()
    list_of_partner = Partner.objects.get(user=request.user).getAllUsersByLevel(level)
    list_of_active_partner = [partner for partner in all_partner if partner.is_active]
    inactive_partner = len(all_partner) - len(list_of_active_partner)
    fisrt_level_user = User.objects.filter(added_by=request.user).count()

    context = {
        'page': 'partners', 
        'partners': all_partner,
        'level_partner': list_of_partner,
        'first_level_user': fisrt_level_user,
        'active_partner': list_of_active_partner,
        'inactive_partner': inactive_partner
    }
    return render(request, 'users/partners.html', context)

users/templates/users/dashboard.html
{% extends 'users/layouts/base.html' %}
{% load static %}

{% block content %}
    {% include 'users/partials/_prices.html' %}
    <div class="row pb-30">
        <div class="col-xl-6">
            <div class="earn-item mb-30">
                <div class="earn-thumb">
                    <img src="{% static 'assets/images/dashboard/earn/01.png' %}" alt="dashboard-earn">
                </div>
                <div class="earn-content">
                    <!-- <h6 class="title">Active deposits in the amount of</h6> -->
                    <h6 class="title">Earned Referral(Benefit)</h6>
                    <ul class="mb--5">
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/usd.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">{{request.user.total_referral_amount_xaf}}</span>
                                <span class="cl-4">XAF</span>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/btc.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">{{request.user.total_referral_amount_usdt}}</span>
                                <span class="cl-4">USDT</span>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/xrp.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">{{request.user.total_referral_amount_tron}}</span>
                                <span class="cl-4">TRON</span>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/eth.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">{{request.user.total_amount_bonus_sub}}</span>
                                <span class="cl-4">Bonus</span>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="earn-item mb-30">
                <div class="earn-thumb">
                    <img src="{% static 'assets/images/dashboard/earn/02.png' %}" alt="dashboard-earn">
                </div>
                <div class="earn-content partner-content d-flex flex-wrap align-items-start justify-content-between">
                    <h6 class="title w-100">All partners</h6>
                    <ul class="mb--5">
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/active.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-4">Active :</span>
                                <span class="cl-1">{{ active_partner|length|default:0 }}</span>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/inactive.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-4">Inactive :</span>
                                <span class="cl-1">{{ inactive_partner|default:0 }}</span>
                            </div>
                        </li>
                    </ul>
                    <div class="total-partner">
                        <span class="total-title">{{partners|length|default:0}}</span>
                        <span>Total</span>
                    </div>
                </div>
            </div>
        </div>
        <!-- <div class="col-lg-6 col-xl-4">
            <div class="earn-item mb-30">
                <div class="earn-thumb">
                    <img src="{% static 'assets/images/dashboard/earn/03.png' %}" alt="dashboard-earn">
                </div>
                <div class="earn-content">
                    <h6 class="title">Earned Referral</h6>
                    <ul class="mb--5">
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/usd.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">0.00</span>
                                <span class="cl-4">USD</span>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/btc.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">0.000000</span>
                                <span class="cl-4">BTC</span>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/xrp.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">0.000000</span>
                                <span class="cl-4">XRP</span>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/eth.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">0.000000</span>
                                <span class="cl-4">ETH</span>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-xl-4">
            <div class="earn-item mb-30">
                <div class="earn-thumb">
                    <img src="{% static 'assets/images/dashboard/earn/04.png' %}" alt="dashboard-earn">
                </div>
                <div class="earn-content">
                    <h6 class="title">Earned Deposits</h6>
                    <ul class="mb--5">
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/usd.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">0.00</span>
                                <span class="cl-4">USD</span>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/btc.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">0.000000</span>
                                <span class="cl-4">BTC</span>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/xrp.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">0.000000</span>
                                <span class="cl-4">XRP</span>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/eth.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">0.000000</span>
                                <span class="cl-4">ETH</span>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div> -->
        <!-- <div class="col-lg-6 col-xl-4">
            <div class="earn-item mb-30">
                <div class="earn-thumb">
                    <img src="{% static 'assets/images/dashboard/earn/05.png' %}" alt="dashboard-earn">
                </div>
                <div class="earn-content">
                    <h6 class="title">Payout</h6>
                    <ul class="mb--5">
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/usd.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">0.00</span>
                                <span class="cl-4">USD</span>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/btc.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">0.000000</span>
                                <span class="cl-4">BTC</span>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/xrp.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">0.000000</span>
                                <span class="cl-4">XRP</span>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/eth.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">0.000000</span>
                                <span class="cl-4">ETH</span>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div> -->
        <!-- <div class="col-lg-6">
            <div class="earn-item small-thumbs mb-30">
                <div class="earn-thumb">
                    <img src="{% static 'assets/images/dashboard/earn/06.png' %}" alt="dashboard-earn">
                </div>
                <div class="earn-content">
                    <h6 class="title">Latest Registered Partner</h6>
                    <ul class="mb--5">
                        <li>
                            <div class="cont w-100 p-0">
                                <span class="cl-1">{{request.user.user_partner.first_partern_added}}</span>
                                <a href="Mailto:demo@mail.com" class="cl-4">Email: <span class="__cf_email__" data-cfemail="f59190989ab598949c99db969a98">[email&#160;protected]</span></a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="earn-item small-thumbs mb-30">
                <div class="earn-thumb">
                    <img src="{% static 'assets/images/dashboard/earn/07.png' %}" alt="dashboard-earn">
                </div>
                <div class="earn-content">
                    <h6 class="title">The last Referral Calculation</h6>
                    <ul class="mb--5">
                        <li>
                            <div class="icon">
                                <img src="{% static 'assets/images/dashboard/earn/usd.png' %}" alt="dashboard-earn">
                            </div>
                            <div class="cont">
                                <span class="cl-1">0.00</span>
                                <span class="cl-4">USD</span>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div> -->
    </div>
    
{% endblock content %}
    
    


users/templates/users/setting.html

    {% extends 'users/layouts/base.html' %}
    {% load static %}
    
    {% block content %}

    <!-- {% include 'users/partials/_prices.html' %} -->
        <div class="partners">
            <h4 class="main-title">Settings</h4>
            
            {% include 'partials/_messages.html' %}

            {% if form.errors %}
                <div class="alert-danger">{{ form.non_field_errors }}</div>
            {% endif %}

            {% for field in form %}
                <div class="alert danger">{{ field.errors }}</div>
            {% endfor %}
                
            <div class="row mb-30-none">
                <div class="col-lg-6 mb-30">
                    <div class="create_wrapper mw-100">
                        <h5 class="subtitle">Personal Info</h5>
                        <!-- <div class="d-flex align-items-center mb-30">
                            <div class="update_user">
                                <img src="{% static 'assets/images/dashboard/user.png' %}" alt="dashboard">
                            </div>
                            <div class="pl-3">
                                <span class="sub_subtitle cl-title fz-sm d-block">JPEG Or PNG 500 x 500px</span>
                                <label for="update_profile" class="custom-button m-0 mt-2 lh-40 h-40">Browse Image</label>
                                <input type="file" id="update_profile" class="profile_update_input">
                            </div>
                        </div> -->
                        <form class="create_ticket_form row mb-30-none" method="post" action="{% url 'accounts:update-user' %}">
                            {% csrf_token %}
                            <div class="create_form_group col-sm-12">
                                <label for="account_name">First Name:</label>
                                <input type="text" id="account_name" placeholder="First Name" name="first_name" value="{{ request.user.first_name }}">
                            </div>
                            <div class="create_form_group col-sm-12">
                                <label for="last_name">Last Name:</label>
                                <input type="text" id="last_name" placeholder="Last Name" name="last_name" value="{{ request.user.last_name }}">
                            </div>
                            <div class="create_form_group col-sm-12">
                                <label for="account_email">Your Email Address:</label>
                                <input type="email" id="account_email" placeholder="Enter your Email"  name="email" value="{{ request.user.email }}">
                            </div>
                            <div class="create_form_group col-sm-12">
                                <label for="account_mobile">Mobile No:</label>
                                <input type="text" id="account_mobile" placeholder="Enter your Mobile No"  name="phone" value="{{ request.user.phone }}">
                            </div>
                            <!-- <div class="create_form_group col-sm-12">
                                <label for="account_address">Address:</label>
                                <input type="text" id="account_address" placeholder="Enter Address">
                            </div> -->
                            <!-- <div class="create_form_group col-sm-6">
                                <label for="account_city">City:</label>
                                <input type="text" id="account_city" placeholder="Enter your City">
                            </div> -->
                            <!-- <div class="create_form_group col-sm-6">
                                <label for="account_state">State</label>
                                <input type="text" id="account_state" placeholder="Enter your State">
                            </div> -->
                            <div class="create_form_group col-sm-12">
                                <label for="country_name">Country:</label>
                                <input type="text" id="country_name" placeholder="Enter your Country"  name="country" value="{{ request.user.country }}">
                            </div>
                            <div class="create_form_group col-sm-6 align-self-end">
                                <button type="submit" class="custom-button border-0">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-6 mb-30">
                    <div class="create_wrapper mw-100">
                        <h5 class="subtitle">payment system</h5>
                        <form class="create_ticket_form row mb-30-none" method="post" action="{% url 'accounts:update_user_payment_system' %}">
                            {% csrf_token %}
                            <!-- <div class="create_form_group col-sm-12">
                                <label for="perfect_money">Perfect Money:</label>
                                <input type="text" id="perfect_money" value="U12\34567">
                            </div>
                            <div class="create_form_group col-sm-12">
                                <label for="payer_account">Your Payeer acc no:</label>
                                <input type="text" id="payer_account" value="P1234567">
                            </div>
                            <div class="create_form_group col-sm-12">
                                <label for="payment_gateway">Paypal:</label>
                                <input type="text" id="payment_gateway" value="Johndoe@gmail.com">
                            </div> -->
                            <div class="create_form_group col-sm-12">
                                <label for="bitcoin_account_no">Your USDT acc no:</label>
                                <input type="text" id="usdt_acc" name="usdt_acc" value="{{ request.user.tron_account_number }}">
                            </div>
                            <div class="create_form_group col-sm-12">
                                <label for="litecoin_account">Your TRON acc no:</label>
                                <input type="text" id="tron_acc" name="tron_acc" value="{{ request.user.usdt_account_number }}">
                            </div>
                            <!-- <div class="create_form_group col-sm-12">
                                <label for="dogecoin_account">Your Dogecoin acc no:</label>
                                <input type="text" id="dogecoin_account" value="55550002220022">
                            </div>
                            <div class="create_form_group col-sm-12">
                                <label for="ethereum_account">Your Ethereum acc no:</label>
                                <input type="text" id="ethereum_account" value="55550002220022">
                            </div> -->
                            <div class="create_form_group col-sm-6 align-self-end">
                                <button type="submit" class="custom-button border-0">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
                
                <div class="col-lg-6 mb-30">
                    <div class="create_wrapper mw-100">
                        <h5 class="subtitle">Change Passowrd</h5>
                        <form class="create_ticket_form row mb-30-none" method="post" action="{% url 'accounts:update_password' %}">
                            {% csrf_token %}
                            <div class="create_form_group col-sm-12">
                                <label for="old_pass">Old Passowrd:</label>
                                <input type="password" id="old_pass" placeholder="Enter your Old Password" name="old_password">
                            </div>
                            <div class="create_form_group col-sm-12">
                                <label for="new_pass">New password::</label>
                                <input type="password" id="new_pass" placeholder="Enter your new password:" name="new_password1">
                            </div>
                            <div class="create_form_group col-sm-12">
                                <label for="repeat_pass">Repeat the new password::</label>
                                <input type="password" id="repeat_pass" placeholder="Repeat your new password:" name="new_password2">
                            </div>
                            <div class="create_form_group col-sm-6 align-self-end">
                                <button type="submit" class="custom-button border-0">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    <!-- </div> -->
    
{% endblock %}